services:
  api:
    image: liminalis-api:local
    build:
      context: .
      dockerfile: apps/api/Dockerfile

  migrate:
    image: liminalis-api-migrate:local
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: migrate

  web:
    image: liminalis-web:local
    build:
      context: .
      dockerfile: apps/web/Dockerfile

  admin:
    image: liminalis-admin:local
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
